### ISSUE TITLE
Add support for disabling plugin via environment variables

### ISSUE THREAD

**Issue by timvink** [aklajnert/mkdocs-simple-hooks#10]
Nice plugin!

I'm considering to use to run some scripts that generates assets (figures, tables) on_pre_build, however I only want to do that when deploying.

MkDocs now has support for environment variables in the `mkdocs.yml` file (https://www.mkdocs.org/user-guide/configuration/#environment-variables)

I propose adding another argument `enabled` like so:

```
- mkdocs-simple-hooks:
     enabled: true
     hooks:
      hook-name: "your.module:hook_function"
```

Users could then configure an environment variable to optionally switch off:

```
enabled: !ENV ENABLE_MKDOCS_SIMPLE_HOOKS
```

Should be very quick to build, here's an example:

- https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/3303a8885f0c6bee2899b5dd70a5a4f981f28331/mkdocs_git_revision_date_localized_plugin/plugin.py#L41
- https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/3303a8885f0c6bee2899b5dd70a5a4f981f28331/mkdocs_git_revision_date_localized_plugin/plugin.py#L59-L60

If you want I can also provide a PR.

**Comment by aklajnert** [comment]
Hi @timvink, thanks for the suggestion. I think in general it can be a nice improvement for the plugin.  
Currently, you can resolve the environment variable within your hook function and early return if the variable is set or not, but this would be more straightforward I think.  
I'm a bit busy with other stuff right now, but feel free to raise a PR to implement this change.

**Comment by aklajnert** [comment]
Closed by #11

**Comment by timvink** [comment]
FYI, I promoted this plugin & this specific feature in the blogpost on [Reproducible Reports with MkDocs](https://timvink.nl/reproducible-reports-with-mkdocs/)

**Comment by aklajnert** [comment]
Great, thanks. I'll read this post later when I'll find some free time :)
