### ISSUE TITLE
Update example use case

### ISSUE THREAD

**Issue by timvink** [aklajnert/mkdocs-simple-hooks#12]
The example use case doesn't do justice to this plugin imho, as 

1) embedding external files is well documented (see https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#embedding-external-files)
2) copying `README.md` into `index.md` creates unnecessary `git diff`s  

```shell
pip install mkdocs-material
```

```yaml
# mkdocs.yml
markdown_extensions:
  - pymdownx.snippets
```

```markdown
# index.md
--8<--​ "README.md"
```

I think this plugin really shines when you're creating assets (on_pre_build) for your documentation. I'm biased, but I like the combination with [mkdocs-table-reader-plugin](https://github.com/timvink/mkdocs-table-reader-plugin) , [mkdocs-charts-plugin](https://github.com/timvink/mkdocs-charts-plugin) and [mkdocs-markdownextradata-plugin](https://github.com/rosscdh/mkdocs-markdownextradata-plugin).

How about an example with a python function that downloads a random kitty image (https://docs.thecatapi.com/) ? Or the latest XKCD (https://xkcd.com/info.0.json) ? Or just saves a machine learning model performance metric into a `docs/assets/metrics.json` file you can insert into your site?

Happy to provide a PR if you're interested.

**Comment by aklajnert** [comment]
Honestly, the example in the README is the exact reason why I've created this plugin. I didn't know that you can embed external files (not sure if it was available at the time I needed it).  
But yeah, I think if you have a better example of how to demonstrate the plugin usability then sure, let's do this. Please submit a PR with your proposal.
