### ISSUE TITLE
Push the updated README to https://pypi.org/project/mkdocs-simple-hooks/

### ISSUE THREAD

**Issue by davidyuk** [aklajnert/mkdocs-simple-hooks#3]
Including #2 fix.

**Comment by aklajnert** [comment]
Oh, I forgot that it is displayed also on Pypi, that can be misleading. Thanks for report @davidyuk

**Comment by aklajnert** [comment]
Done: https://pypi.org/project/mkdocs-simple-hooks/0.1.2/
