### ISSUE TITLE
The module path can't be nested

### ISSUE THREAD

**Issue by honzajavorek** [aklajnert/mkdocs-simple-hooks#4]
Hi, thanks for this project, it's a great idea. I discovered the plugin has problems with module names like `my.nested.module.name`. The `__import__()` doesn't seem to handle it well.

I tried to replace it with `importlib.import_module()` and all started to work. Is there a specific reason why `__import__()` is used? If not, would you accept a Pull Request fixing this?

**Comment by aklajnert** [comment]
Hi, there isn't any particular reason to choose `__import__()` over `importlib`. I think I wasn't aware of the `importlib` at the time when I was writing this plugin, and `__import__()` was good enough for me.  
If switching to `importlib` won't damage the current functionality (by reading the documentation it seems it shouldn't), then I'd be happy to accept a PR with such change.  
Thanks!
